### ISSUE TITLE
Jr mod Permissions

### ISSUE THREAD

**Issue by PathosIV** [PathosIV/F-A#1]
Jr mods are unable to Tempmute/kick players

**Comment by PathosIV** [comment]
Perms edited, please test the ability to tempban, warn, tempmute.

**Comment by Kolioli** [comment]
None are working, it comes up with "You do not have access to this. Contact an admin if you feel this is in error"

**Comment by PathosIV** [comment]
New permissions for all staff: 
http://wiki.ess3.net/wiki/Command_Reference/Perm
https://dev.bukkit.org/projects/ban-management/pages/commands-permissions

    - bukkit.command.gamemode
    - ChestShop.shop.*
    - essentials.gamemode
    - essentials.joinfullserver
    - essentials.jump
    - worldedit.navigation.thru.command
    - essentials.chat.ignoreexempt
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.ban.notify
    - essentials.tempban
    - essentials.tempban.exempt
    - essentials.tempban.offline
    - bm.command.tempban
    - bm.command.tempban.offline
    - bm.command.unban
    - bm.command.unban.own
    - bm.command.warn          
    - bm.command.warn.offline
    - bm.command.tempwarn      
    - bm.command.tempwarn.offline
    - bm.command.banlist
    - bm.command.banlist.players
    - bm.command.banlist.ips
    - bm.command.banlist.ipranges
    - bm.command.activity
    - bm.command.clear.banrecords
    - bm.command.clear.kicks
    - bm.command.clear.muterecords
    - bm.command.clear.notes
    - bm.command.clear.reports
    - bm.command.clear.warnings
    - bm.command.addnote
    - bm.command.notes
    - bm.command.notes.online
    - bm.command.bminfo
    - bm.command.bminfo.playerstats
    - bm.command.bminfo.connection
    - bm.command.bminfo.ipstats
    - bm.command.bminfo.alts
    - bm.command.bminfo.website
    - bm.command.tempbanip
    - bm.command.unbanip
    - bm.command.kick
    - bm.command.mute
    - bm.command.mute.override
    - bm.command.tempmute
    - bm.command.tempmute.offline
    - bm.command.unmute.own
    - bm.command.banname
    - bm.command.banname.override
    - bm.command.tempbanname
    - bm.command.tempbanname.override
    - bm.command.unbanname
    - bm.notify.ban
    - bm.notify.tempban
    - bm.notify.unban
    - bm.notify.banip
    - bm.notify.tempbanip
    - bm.notify.unipban
    - bm.notify.mute
    - bm.notify.muted
    - bm.notify.tempmute
    - bm.notify.unmute
    - bm.notify.muteip
    - bm.notify.mutedip
    - bm.notify.tempmuteip
    - bm.notify.unmuteip
    - bm.notify.baniprange
    - bm.notify.tempbaniprange
    - bm.notify.unbaniprange
    - bm.notify.kick
    - bm.notify.reports
    - bm.notify.reports.open
    - bm.notify.reports.assigned
    - bm.notify.warn
    - bm.notify.tempwarn
    - bm.notify.duplicateips
    - bm.notify.notes
    - bm.notify.notes.join
    - bm.notify.denied.player
    - bm.notify.denied.ip
    - bm.notify.banname
    - bm.notify.tempbanname
    - bm.notify.unbanname
    - bm.command.reports.list.others
    - bm.command.reports.teleport
