### ISSUE TITLE
MCA needle and Doggy Styles dog whistle

### ISSUE THREAD

**Issue by MotoMischief** [PathosIV/F-A#19]
The MCA Needle and Doggy Styles dog whistle have the same crafting recipe. It always tends to lean towards MCA instead of the Doggy Styles dog whistle no matter how it is put into the crafting table. I found this problem out pretty quickly on my single player world and I had to spawn in a dog whistle because there was no other way to make the dog whistle or find an alternative way to make it.

**Comment by PathosIV** [comment]
This issue is completed. 
X's are empty spots in the enchanted table.

Doge Whistle recipe is now: 

X   X  Wood stick
X  Iron Stick X
Iron Stick  X  X
