### ISSUE TITLE
Ban/ Tempban Request

### ISSUE THREAD

**Issue by Kolioli** [PathosIV/F-A#5]
Yesterday, 8/22/2017, Spurius187 was reported to have killed a tamed dinosaur, i went to check it out and /pr said it was true.

**Comment by PathosIV** [comment]
Completed
23.08 12:26:32 [Server] INFO spurius187 has been temporarily banned for 2 days by Console for Tamed Dino killing is not aĺlowed.
23.08 12:26:32 [Disconnect] User spurius187 has disconnected, reason: You have been temporarily banned for Tamed Dino killing is not aĺlowed.
