### ISSUE TITLE
Enchanted books

### ISSUE THREAD

**Issue by Kolioli** [PathosIV/F-A#6]
Players are starting to report that enchanted book arent actually enchanting, and form into some sort of enchantment book without enchantments. When tried to used it crashed the player.

**Comment by 4f6f3b** [comment]
Is it possible to get a crash report file from that player?

**Comment by Kolioli** [comment]
It was awhile back, but it keeps happening so ill ask the next player

**Comment by PathosIV** [comment]
This is no longer an issue. I'm keeping the Enchanted books disabled. To keep the enchanted equipment still fairly rare, I'm leaving enchanted books disabled. The Unenchanting table can now break down enchanted item, so this is used to make sure people don't start mass producing all the enchanted books.
